general_settings:
  store_model_in_db: true
  store_prompts_in_spend_logs: true


model_list:
  - model_name: gpt-5-smart
    litellm_params:
      model: gpt-5
      reasoning:
        effort: high
        summary: detailed
      text:
        verbosity: high
      api_key: os.environ/OPENAI_API_KEY
